[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "car_sales_agent"
version = "0.1.0"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "AI Car Sales Agent"
requires-python = ">=3.9" 